### ISSUE TITLE
Allow removal of menu items

### ISSUE THREAD

**Issue by hlashbrooke** [wearerequired/admin-menu-manager#12]
It would be great if items could be removed from the menu completely. You would obviously need a way to be able to restore them, so a possible UI could be a a box that appears below the 'Edit Menu' button while you're in edit mode where you can drop unneeded menu items. They will then remain there and can be dragged back into place in the future.

I'm not sure how possible that will be, but it would be a great add-on to what is already an awesome plugin.

**Comment by swissspidy** [comment]
Hey @hlashbrooke, thanks for submitting this! Such a feature would really help decluttering the admin menu.

As this is closely related to #3 UI-wise, so I will have to think about a nice way to interated both. A "dropbox" in the bottom (or maybe on the right) definitely sounds interesting.

**Comment by neverything** [comment]
I thought about the same feature as @hlashbrooke too last night. Maybe a fly-out when you are in edit mode that allows you to hide the menu item for certain user roles or everyone.

The restore with a dropbox or similar to inactive but configured widgets could be the solution to restore the menu items.

**Comment by hlashbrooke** [comment]
Yeah - it would link up with #3 nicely. A dropbox would be the most obvious UI to me, but as long as it's a logical way to store the items until they're needed again then it will be very useful.

**Comment by swissspidy** [comment]
I'm moving this to the 2.0.0 milestone, where I want to make a big rewrite of the plugin in order to accommodate for the various UI changes coming up:
- Removing & restoring items (#12 & #16)
- Editing items (#1 & #2)
- Adding new items (#3)

For now the plugin works as expected and makes for a nice version 1.0.

**Comment by hlashbrooke** [comment]
I think that's a good move - no point in delaying v1 for features that can wait for v2 :)

**Comment by swissspidy** [comment]
A sneak peek at what I've been working on:

![bildschirmfoto 2015-05-02 um 17 28 12](https://cloud.githubusercontent.com/assets/841956/7441630/a664c13e-f0f0-11e4-8e50-2e176cb606df.png)

**Comment by swissspidy** [comment]
This is currently integrated in the `develop` branch. Trashing & restoring menu items works well so far, but needs more testing. New issues can be opened for found bugs.

**Comment by hlashbrooke** [comment]
That screenshot looks awesome - I'll check out the develop branch a little later too :)
