### ISSUE TITLE
Backbone Rewrite

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/admin-menu-manager#18]
Just like with the [User Feedback Plugin](https://github.com/wearerequired/simple-user-adding), the Admin Menu Manager is getting bigger and bigger. That's why a more modular rewrite using Backbone.js makes sense to me.

We could separate the logic, use event triggers, and much more.

**Comment by neverything** [comment]
I personally think this is a great idea, it also makes it possible to have a modular approach especially for the features planned for 2.0.0.
