### ISSUE TITLE
Moving plugin activated Sub-Menu to Top-Level doesn't work

### ISSUE THREAD

**Issue by neverything** [wearerequired/admin-menu-manager#19]
Using the https://github.com/wearerequired/WP-Widget-Disable plugin, I wanted to drag out the "Appearance -> Disable Widgets" menu item to the top-level. Unlike with "Themes" it didn't work as expected:

![screenshot 2015-04-07 11 13 01](https://cloud.githubusercontent.com/assets/368120/7020229/9e419668-dd17-11e4-80fb-b56cb0c0b2df.png)

After a save and refresh it's back in it's original position:

![screenshot 2015-04-07 11 17 38](https://cloud.githubusercontent.com/assets/368120/7020240/b8201ba4-dd17-11e4-9fd2-bf3e2baeafc4.png)

**Comment by swissspidy** [comment]
@neverything How dare you to submit a bug report?! ;)
Jokes aside, are you getting any JS errors when moving the menu item around?

**Comment by neverything** [comment]
@swissspidy hehe, sorry didn't have time to fix it yet... 

On drop I am getting:

![screenshot 2015-04-07 11 22 00](https://cloud.githubusercontent.com/assets/368120/7020326/63db2af6-dd18-11e4-9cfc-57765d8d33d8.png)

**Comment by neverything** [comment]
Works like a charm! Thanks
