### ISSUE TITLE
Filter to Turn Off Editing

### ISSUE THREAD

**Issue by fgilio** [wearerequired/admin-menu-manager#28]
A filter so that users have a easy way to Turn Off Editing functionality, thus preventing the enqueuing of scrips, styles and a little markup. All in a couple lines of code in functions.php

Useful when you finished editing the menu and don't want to load all that every time.

**Comment by swissspidy** [comment]
Interesting idea. And basically already done, but only in the dev version based on another comment before.

Thanks!

**Comment by fgilio** [comment]
Glad it's useful!

**Comment by swissspidy** [comment]
There's now an `amm_user_can_change_menu` filter which can be used to prevent enqueueing the scripts and styles.
