### ISSUE TITLE
You do not have sufficient permissions to access this page.

### ISSUE THREAD

**Issue by NickHeurter** [wearerequired/admin-menu-manager#34]
After installing beta version 2.0 I tried to reach my posts but I got the following error message: 'You do not have sufficient permissions to access this page.'. After disabling the plugin I could reach my posts again.

**Comment by swissspidy** [comment]
Huh, interesting. Thanks for your report.

I guess I might have broken something while refactoring some parts of the code recently. So far in the beta that message only appeared for some plugins.

**Comment by swissspidy** [comment]
Closing for now as it seems to work in master (fingers crossed).
