### ISSUE TITLE
New items disappear

### ISSUE THREAD

**Issue by blogmom** [wearerequired/admin-menu-manager#38]
using 2.0.0-alpha:
Steps:  
1.  Create a new item, change its name, click checkbox icon to save it.   Then create another new item and give it a unique name.  Two new items.  Click check icon to close Edit mode.
2. click Edit Items, then click one of the new items  (the Edit box pops up)
3. Don't make changes, but click on another item in the menu (any, new or existing item).   Then click on another (any).  Now there should be three Edit pop-ups open (which seems to be an already-reported open bug)
4. Click X to cancel.  
5. All New items are gone.

**Comment by swissspidy** [comment]
Ugh, I wished this would finally work. The WordPress admin menu is super annoying to work with.

Since you created two new items, does this also happen when only trying to add 1 new custom item?

**Comment by blogmom** [comment]
Yes, the steps I described happen with one item.

Actually.

The issue is related to the Cancel button.   simply entering Edit mode then clicking Cancel icon causes all New Items to disappear. 

Sorry I didn't notice that sooner.

**Comment by swissspidy** [comment]
Okay, so yeah, this is not a Cancel button, but the button to reset the whole menu. I know, that sucks. Still need to figure out a good way to support both actions.

Right now, the only way to cancel is to either click undo multiple times or refresh the page.

**Comment by blogmom** [comment]
I kindly suggest moving "Reset" into the pop-up menu under Import/Export.  With a new confirmation pop-up after clicking  :)

**Comment by swissspidy** [comment]
Let's fix this!

Needs a better icon for the pop-up menu though so it's clear to everyone it's a pop-up menu.

Also, I'll try to tweak the styling a bit, i.e. adding some background color on hover and stuff like that.

**Comment by swissspidy** [comment]
The button with the x icon now cancels editing. Reset has been moved under the pop-up menu.

<img width="172" alt="screen shot 2017-02-18 at 16 38 11" src="https://cloud.githubusercontent.com/assets/841956/23094410/b9542a96-f5f8-11e6-8f4a-ae087c778370.png">
