### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by JasonTheAdams** [wearerequired/admin-menu-manager#41]
Hey! Been watching this plugin for a while and I'm pretty excited for it! When I saw there was an alpha of 2.0 I was pretty interested in testing it out.

I grabbed it, put it in the plugins, and ran `composer install --no-dev`. It mostly worked, but I got the following error:
```
Loading composer repositories with package information
Updating dependencies
  - Installing wearerequired/wp-requirements-check (dev-master 0d9f602)
    Cloning 0d9f602ed83def11f97c07ee76ad204cc1ba247f from cache

Writing lock file
Generating autoload files
> "vendor/bin/phpcs" --config-set installed_paths vendor/wp-coding-standards/wpcs
sh: vendor/bin/phpcs: No such file or directory
Script "vendor/bin/phpcs" --config-set installed_paths vendor/wp-coding-standards/wpcs handling the post-update-cmd event returned with error code 127
```

**Comment by swissspidy** [comment]
Thanks for your report!

This is a warning from Composer about missing folders that you can basically ignore. Why? Right now, we use Composer to require some tools for easier development (`require-dev`). If installed (i.e. when not using `--no-dev`), the `post-install-cmd` and `post-update-cmd` directives would configure these tools.

When using `composer install --no-dev`, these files will be missing and the directives aren't working. That doesn't prevent the plugin from running though, as it's really just for development.

With that being said, it's not ideal and I'll probably remove these directives as these tools should be installed globally on one's computer if they want to develop / contribute to the plugin.

**Comment by JasonTheAdams** [comment]
I had a feeling that was the issue, but wanted to report it. Feel free to either leave this open as a reminder or close it. :)
