### ISSUE TITLE
WP_Requirements_Check

### ISSUE THREAD

**Issue by ahmedofali** [wearerequired/admin-menu-manager#43]
Directly After Activation I Found this error 
Fatal error: Class 'WP_Requirements_Check' not found in /var/www/html/proj_name/wp-content/plugins/admin-menu-manager-master/admin-menu-manager.php on line 38

**Comment by swissspidy** [comment]
Hey there,

Did you use the version from WordPress.org or the one on GitHub? For the latter, you need to run `composer install` first. And then `npm install && grunt` to generate all the CSS and JS.

**Comment by ahmedofali** [comment]
It's Working Now Thanks For the steps.
