### ISSUE TITLE
Prepare for Beta

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/admin-menu-manager#50]
Put the last finishing touches on the plugin and fix the most obvious bugs. Some I've noticed two weeks ago:

* [x] Menu items sometimes don't stay at their position and get added to the end
* [x] Custom menu items sometimes disappear
* [x] Slugs/Links sometimes change (e.g. with the Email Subscribers plugin)
* [ ] When moving a top-level menu item, the first sub level item might be moved instead

After that, create a 2.0.0 Beta 1 release here on GitHub an perhaps even upload it to the WordPress.org plugin directory (but keep the stable tag at 1.0.1).

**Comment by theperfectwill** [comment]
Awesome! Blessings and creativity to you @swissspidy. Thanks for the generous update post 👍 💯 🥇
