### ISSUE TITLE
Can't get sub menus back to original position

### ISSUE THREAD

**Issue by tmconnect** [wearerequired/admin-menu-manager#8]
I dragged the "Add New" item from the "Pages" menu into the root of the admin menu. After that the "Pages" menu doesn't have any submenu and therefore I can't set the "Add New" menu item not back to the "Pages" menu as a sub item.

**Comment by swissspidy** [comment]
Thanks for reporting this!

I also thought about this before and made some comments in the JS about it [here](https://github.com/wearerequired/admin-menu-manager/blob/master/js/src/admin-menu-manager.js#L9) and [here](https://github.com/wearerequired/admin-menu-manager/blob/master/js/src/admin-menu-manager.js#L48). I will have to think about a nice way to implement this, especially in relation to #3.

**Comment by swissspidy** [comment]
@tmconnect I just pushed some changes to the `develop` branch that help improve this. I successfully tested with the scenario you described as well as making Jetpack a sub item of the Dashboard, or Design a sub item of Comments.

There are just a couple of things I want to work as a follow-up, but this specific bug should be fixed. Can you test that please?

**Comment by tmconnect** [comment]
@swissspidy Thanks for your quick reply. I tested the `develop` branch and yes it works as aspected. Now I'm able to get a menu item as a sub menu into a main menu item. This means, that an original sub menu item could get back to its original position.

Thanks
Thomas
